name: Terraform Plan and Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        env:
          client_id: ${{ secrets.ARM_CLIENT_ID }}
          client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.ARM_TENANT_ID }}
        run: terraform init

      - name: Terraform Plan
        env:
          client_id: ${{ secrets.ARM_CLIENT_ID }}
          client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.ARM_TENANT_ID }}
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          client_id: ${{ secrets.ARM_CLIENT_ID }}
          client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.ARM_TENANT_ID }}
        run: terraform apply -auto-approve
